name = "StrEntities"
desc = "Extension for StrLiterals, adds support for entities in formatted strings"
authors = ["ScottPJones <scottjones@alum.mit.edu>"]
keywords = ["Strings", "Literals", "Entities", "Unicode", "HTML", "LaTeX", "Emoji"]
license = "MIT"
uuid = "f6164076-6934-4707-9ef0-ff39da4345e6"

[deps]
Pkg     = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test    = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unicode = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

StrTables            = "9700d1a9-a7c8-5760-9816-a99fda30bb8f" # ekt5t6nt8g0cqhjb
LaTeX_Entities       = "9927f19a-46ce-5bdd-a20a-f46a78b61e3d" # ok2sdq4u5xwlc6b0
Emoji_Entities       = "fd8f23de-bd2f-5c75-921c-0c9ab51355f5" # 4p6o3reehca95put
HTML_Entities        = "7693890a-d069-55fe-a829-b4a6d304f0ee" # xp05kd5mamt92yhj
Unicode_Entities     = "a8aa15d3-c567-5e9f-b6cc-4b0f97f09cf7" # c1luci97ry8fxdt7
StrLiterals          = "627f7b36-cfa1-4420-8f93-de9d4fe56cdc" # 8462oq09ek07knos
